const assortment = [
  {
    title: "berenguer ramon j",
    img: "",
    type: "brut cava",
    smaak: "droog (< 12 gr/L)",
    druiven: "macabeu, parellada, xarel-lo",
    rijping: "10 maanden",
    prijs: "15,95",
    uitverkocht: false,
  },
  {
    title: "berenguer ramon &dash; rosé",
    img: "./assets/berenguer-rose.png",
    type: "brut cava rosé",
    smaak: "droog (&lt; 12 gr/L)",
    druiven: "macabeu, parellada, xarel&dash;lo",
    rijping: "9&dash;10 maanden",
    prijs: "&euro; 16,95",
    uitverkocht: true,
  },
  {
    title: "Llopart Brut",
    img: "./assets/Llopart-Brut-Reserva-1500x430-eng-705x202.png",
    type: "brut corpinnat reserva",
    smaak: "droog (&lt; 12 gr/L)",
    druiven: "macabeu, parellada, xarel&dash;lo",
    rijping: "18&dash;20 maanden",
    prijs: "&euro; 23,95",
    uitverkocht: true,
  },
  {
    title: "Llopart Brut &dash; rosé",
    img: "./assets/Llopart-Rose-1500x430-esp-eng-705x202.png",
    type: "brut corpinnat rosé reserva ",
    smaak: "droog (&lt; 12 gr/L)",
    druiven: "monastrell, garnatxa, pinot noir",
    rijping: "18&dash;20 maanden",
    prijs: "&euro; 23,95",
    uitverkocht: true,
  },
  {
    title: "Llopart Integral",
    img: "./assets/Llopart-Integral-1500x430-esp-eng-705x202.png",
    type: "brut nature corpinnat reserva",
    smaak: "zeer droog (&lt; 3 gr/L)",
    druiven: "parellada, xarel&dash;lo, Chardonnay",
    rijping: "24 maanden",
    prijs: "&euro; 25,95",
    uitverkocht: true,
  },
  {
    title: "Llopart Microcosmos",
    img: "./assets/Llopart-Micro-1500x430-eng-705x202.png",
    type: "brut nature corpinnat rosé reserva",
    smaak: "zeer droog (&lt; 3 gr/L)",
    druiven: "pinot noir, monastrell, fruit",
    rijping: "24 maanden",
    prijs: "&euro; 29,95",
    uitverkocht: true,
  },
  {
    title: "Llopart Ex Vite",
    img: "./assets/Llopart-Exvite-1500X430-eng-705x202.png",
    type: "brut nature corpinnat <br> gran reserva",
    smaak: "zeer droog (&lt; 3 gr/L)",
    druiven: "macabeu, xarel&dash;lo",
    rijping: "90 maanden",
    prijs: "&euro; 61,95",
    uitverkocht: true,
  },
];
